name: IK Client Theme
type: theme
base theme: classy
package: IK
version: VERSION
core_version_requirement: ^9

libraries:
  - ik_client/global-styling

regions:
  header: 'Header'
  highlighted: 'Highlighted'
  content: 'Content'
  footer: 'Footer'

ckeditor_stylesheets:
  - styles/css/style.css