name: IK Client Theme
type: theme
base theme: classy
package: IK
version: VERSION

libraries:
  - ik_client/global-styling

regions:
  header: 'Header'
  highlighted: 'Highlighted'
  content: 'Content'
  pre_footer: 'Pre-Footer'
  footer: 'Footer'

ckeditor_stylesheets:
  - styles/css/style.css